[package]
name = "arrays-and-tuples"
version = "0.1.0"
authors = ["Jack Parsons <jcksnparsons@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
